app/channels/import_channel.rb, app/jobs/raw_input_transform_job.rb, app/models/import_result.rb, app/views/imports/show.html.haml, config/cable.yml, config/routes.rb, spec/features/csv_import_spec.rb
This PR adds ActionCable to the app and uses it to update the counts on an Import show page. It's actually pretty fun to see the numbers zoom along as workers process the import! 😄
=> Dynamic import show page

app/controllers/sources_controller.rb, app/helpers/application_helper.rb, app/models/rankable.rb, app/models/source.rb, app/models/source_resolver.rb, app/views/layouts/application.html.haml, app/views/sources/index.html.haml, app/views/sources/new.html.haml, config/routes.rb, spec/fabricators/source_fabricator.rb, spec/features/create_source_spec.rb, spec/features/csv_import_spec.rb, spec/features/list_imports_spec.rb, spec/features/list_sources_spec.rb, spec/features/list_tags_spec.rb, spec/models/source_resolver_spec.rb, spec/models/source_spec.rb, spec/rails_helper.rb
One more piece of the UI puzzle - now Importers can view and create Sources. That last point gets a little interesting because when you create a Source that shifts the ranks of the other Sources we have to adjust things. My answer to this tricky problem is the humble `SourceResolver`. It's got a pretty simple interface - it takes the newly built, but not saved, Source and figures out which other Sources need adjustment and to which ranks. Neato!
The other thing I'd point out is the refactor of `rank_for` on Source - now instead of taking a `Rankable`, it takes a symbol, which is great because it let me remove some `public_send` that had me feeling bad about myself.
Note: I put this PR on top of #123 so the diff here looks bigger than it actually is. ❤️
=> UI for sources

app/models/raw_input_changes.rb, spec/models/raw_input_changes_spec.rb
I decided to add an exception for this case - that felt the most appropriate. I also opted to leave the `error_details` nil because I want to reserve that field for actual ActiveRecord validation errors. This might mean that an Importer could have to decipher exceptions, but maybe that's ok?
I sorta envision a list of exceptions and some explanation on the wiki so that we can help them out that way. Open to thoughts here!
closes #99
=> Only create organizations when website is provided

app/controllers/sources_controller.rb, app/views/sources/index.html.haml, spec/fabricators/source_fabricator.rb, spec/features/list_sources_spec.rb
The idea here is that when you want to see how the ranks of sources are going to resolve, it's helpful to have this in a table.
closes #133
=> Add Source rankings table to list page

data-exploration/burden_csv.rb
This CSV was missing org names. And the headers were not being written to the top of the file.
=> Add organization name to csv and fix headers

app/jobs/data_warehouse_sync_job.rb, spec/jobs/data_warehouse_sync_job_spec.rb
Prior to this commit we'd be going through all the motions of syncing with Redshift even if there was nothing to do! Good catch @gnilekaw.
Note that while I considered reducing the duplication between `nothing_to_sync?` and `update_finished_imports`, I think it's fine. Check this out:
```ruby
> Import.where(state: ImportMicroMachine::FINISHED).any?
(0.3ms)  SELECT COUNT(*) FROM "imports" WHERE "imports"."state" = $1  [["state", "finished"]]
=> false
```
That count statement is going to be really fast and if you extracted the `Import.where(state: ImportMicroMachine::FINISHED)` part, then you'd lose ActiveRecord's ability to optimize.
=> Only sync when there is something to do

app/controllers/imports_controller.rb, app/models/import_result.rb, app/views/imports/index.html.haml, app/views/imports/show.html.haml, app/views/layouts/application.html.haml, app/views/sources/index.html.haml, spec/features/csv_import_spec.rb, spec/features/list_imports_spec.rb, spec/features/list_sources_spec.rb, spec/models/import_result_spec.rb
Add a table to display imports on the imports page more clearly.
Closes https://github.com/artsy/bearden/issues/136
Closes https://github.com/artsy/bearden/issues/134
=> Misc UI tweaks

app/controllers/syncs_controller.rb, app/models/sync_result.rb, app/views/syncs/index.html.haml, config/routes.rb, spec/features/list_syncs_spec.rb
While working on Syncs, it was often annoying that I couldn't see at a glance what had recently happened, so I cooked up this list page. Most of the time it'll look like this:
But when there are Syncs that have happened, it'll be a nice way to see them. I also had ideas about computing an average for how long finished syncs took, but didn't get to it - we'll see if it comes up again.
=> Add list page for viewing recent Syncs

app/models/organization_name.rb
Rather than have this Rankable behave differently than the others, we've
decided that it should rely on Source rank resolution too.
closes #104
=> Remove uniqueness constraint from org name

app/models/import_errors.rb, spec/models/import_errors_spec.rb
Prior to this commit we had implemented passing tag errors up the stack,
but didn't have any specs around it and sure enough, the implementation
wasn't flexible enough. This commit fixes our implementation and also
adds the missing spec.
=> Handle tag errors on import

bin/deploy
Prior to this commit, the log statement would include the PRs on release
that were for previous deploys. My git-foo wasn't good enough to filter
them, so I just resorted to grep.
=> Don't include deploy commits in deploy PR

app/models/data_warehouse.rb, spec/models/data_warehouse_spec.rb
The `load_errors` method was  useful during initial development when uploading data to Redshift was throwing cryptic errors. After living with it for a while though, we haven't encountered even one of these errors after uploading lots of data. _But_ we did get a fatal error when we changed the schema and did not update Redshift. This is way more likely to happen from time to time. So hopefully, this will catch that error and describe it in a helpful way.
=> Remove unused load_error method and add more descriptive PG error

Aptfile
Turns out we were getting failed builds on Circle because Heroku was failing to install charlock_holmes - a quick Google search found this:
https://github.com/brianmario/charlock_holmes/wiki/Installing-charlock-holmes-and-libicu-dev-on-heroku
And I should have know - in fact, I thought about this, but couldn't find an `icu` locally, so figured I was just wrong. Nope!
Anyway, the fix is simple - have Heroku install the lib for us using the apt buildpack.
=> Add Aptfile to install icu on Heroku

spec/rails_helper.rb
Inspired by:
https://github.com/carrierwaveuploader/carrierwave/wiki/how-to:-cleanup-after-your-rspec-tests
But my take was a little less involved. 😉 
Also: how weird is it that `S3Uploader.root` returns a `Proc`??
closes #174
=> Clean up the uploads created during the test run

Gemfile, Gemfile.lock, app/models/organization_builder.rb, app/models/raw_input_changes.rb, app/models/website_resolver.rb, db/migrate/20170417212810_add_status_to_websites.rb, spec/features/csv_import_spec.rb, spec/models/organization_builder_spec.rb, spec/models/raw_input_changes_spec.rb, spec/models/website_resolver_spec.rb, spec/spec_helper.rb
This commit introduces the concept of resolving a website. We take what
comes from the RawInput and do a little normalization (adding protocol)
and then throw that at Faraday which we've configured to follow
redirects.
Note: we do not perform this resolution if there's a match to begin
with, so we're about as conservative with our network calls as we can
be.
Also note: we blow up the whole row if the website 404s.
closes #131
=> Resolve websites to improve matching logic

app/models/auditable.rb, app/models/csv_converter.rb, app/models/email.rb, app/models/location.rb, app/models/organization.rb, app/models/organization_name.rb, app/models/organization_resolver.rb, app/models/organization_tag.rb, app/models/phone_number.rb, app/models/website.rb, lib/tasks/redshift.rake, spec/models/csv_converter_spec.rb, spec/models/organization_resolver_spec.rb, spec/models/organization_spec.rb
NOTE: This PR changes the Redshift schema.
This PR adds a `sources` field to our CSV export. The goal is to export a new field that contains a list of  all the record's sources, ie, `'Source Foo', 'Source Bar', 'Source Qux'`. These sources can come from an `organization`, a `phone_number`, a `location`, and so on. We provide this list as an easy-ish way for end users to query records which contain a given source.
A new module, `Auditable`, fell out of the refactor. All modules that implement PaperTrail now do so via Auditable. This simplified our models and gave us an added method `model.sources`, which returns all the model's source objects. Previously, these were a pain to call: `organization.emails.first.versions.first.actor.source`. Now you can simply use …
=> Export field with array of input sources to Redshift

app/controllers/sources_controller.rb, app/helpers/application_helper.rb, app/models/source_resolver.rb, app/views/sources/_form.html.haml, app/views/sources/edit.html.haml, app/views/sources/index.html.haml, app/views/sources/new.html.haml, config/routes.rb, spec/features/edit_sources_spec.rb, spec/models/source_resolver_spec.rb
This ended up opening a can of worms on the resolution of source ranks.
What I had was too naive - it only considered the case where you were
adding a new Source. What I had to do was improve this code so that it
supported the case of promoting/demoting existing source ranks.
Luckily, I was able to convince the team to only support editing one
Source at a time, so that means that we have far more simple resolution
logic than we might have otherwise. Even still, this broke my brain for
quite a while!
closes #180
=> Edit source

app/jobs/geocode_location_job.rb, app/models/auditable.rb, app/models/rankable.rb, app/models/raw_input.rb, db/seeds.rb, lib/tasks/geocode.rake, spec/jobs/geocode_location_job_spec.rb
Early in the project's life, we assumed Geocoder would be a Source, but
that's not really true.
=> Remove Geocoder as Source

app/models/website_resolver.rb
@madelineb ran into a few situations where a `RawInput` would blow up with
the `Zlib::DataError` exception. Some research turned up this GitHub
Issue:
https://github.com/lostisland/faraday/issues/120
So all this commit does is set that header hoping that it will mean
servers stop using an unsupported compression method.
=> Fix: work around unsupported server compression

Procfile, app/jobs/finalize_import_job.rb, app/jobs/finish_sync_job.rb, app/jobs/geocode_location_job.rb, app/jobs/organization_export_job.rb, app/jobs/parse_csv_import_job.rb, app/jobs/raw_input_transform_job.rb, app/jobs/start_sync_job.rb, app/jobs/sync_management_job.rb
This PR sets up a new worker (`worker_debug`). The idea is to split jobs between the two dynos to get a better diagnosis on memory issues.
=> Add new temporary worker for debugging #AddNewDyno

app/jobs/finish_sync_job.rb, spec/jobs/finish_sync_job_spec.rb
Seein' if this might fix our dupes bug. I'm skeptical, but at least it'll be an accurate filename.
=> Add '.csv' to files uploaded to S3

app/jobs/finish_sync_job.rb, app/models/data_warehouse.rb, app/models/import.rb, app/models/import_micro_machine.rb, spec/jobs/finish_sync_job_spec.rb, spec/models/import_micro_machine_spec.rb
When a sync gets a PG error, there's no way that running the sync again is going to succeed the second or _nth_ time. This PR revises the REVERT state to a FAILED state (lolz). The expected behavior is that the PG errors will be returned by `DataWarehouse::Result`, but instead of `REVERT` moving the sync back to `FINISHED`, it moves it to `ERRORS`. The message to slack is then dispatched and the failed sync will not be picked up again until a dev investigates and changes the state.
Fixes #216
=> Stop trying to sync when there are PG::Errors

.rubocop.yml, app/models/tag.rb, lib/tasks/temporary/tag_type_data_migration.rake
This commit adds a temporary rake task that migrates some tags over to types. Once this migration is complete, this task can be removed from the project. I took inspiration for this from a [thoughtbot][tb] post.
[tb]: https://robots.thoughtbot.com/data-migrations-in-rails
Note that the actor of the OrganizationTag is carried over to the OrganizationType so that we don't lose that signal. This is necessary to ensure that when we resolve the type of an organization our Rankable logic doesn't get goofed up. I note it because, technically, that RawInput record did NOT create that OrganizationType, this rake task did.
closes #228
=> Add temp task to migrate tags to types

Procfile, Procfile.dev, app/jobs/organization_export_job.rb
These jobs are so slow that they gum up the works for all other job types so we're going to put them back on their own queue.
=> Put exports back on their own queue

app/helpers/application_helper.rb, app/views/sources/_form.html.haml, app/views/sources/edit.html.haml, app/views/sources/new.html.haml, spec/features/create_source_spec.rb, spec/features/edit_sources_spec.rb, spec/models/source_resolver_spec.rb
In the UI, ranking a source last corrupts the hierarchy. Given sources such as `[1, 2, 3]`, moving `1` to `3` results in `[2, 3, 3]`. After reviewing the `source_resolver` and not succeeding in reproducing the bug in tests, I determined the bug was probably in the UI. A failing test confirmed this. 
@jonallured and I decided to change a couple things to in the UI to make things more clear. This PR addresses those revisions, among others.
=> Fix source ranking

app/helpers/application_helper.rb
With select options greater than 10 lists appeared thusly `1, 10,  2, 3, ...`. We were calling `sort` on a string value `['10 - Foo Source', 10]`. This PR refactors to sort on the last element of the array, which is an integer.
=> Fix sort method for source select options

lib/tasks/temporary/in_business_data_migration.rake, lib/tasks/temporary/reorder_sources_migration.rake, lib/tasks/temporary/tag_type_data_migration.rake
Reorders the ranks hierarchy. In data we have corrupted rank hierarchies, such as `[1,2,3,4,5,7,8,9,10,11,12,13,13]`. 
This migration will renumber ranks with a new hierarchy.  In the case above, starting after `5`, each item will be renumbered: `7` => `6`, `8` => `9`. 
Notice there is a tie in the last two items, `13` and `13`. How do we know which one comes first? Luckily it doesn't matter. If the rank is lower than one, then the source won't be selected for export, so we can safely ignore this detail.
To see the migration it's more clean [here](https://github.com/artsy/bearden/pull/256/commits/15417ff474dff5514618aea84de9863092d543b9). The other commit adds a namespace for other rake tasks.
=> Source rank migration

lib/tasks/redshift.rake
Syncs were failing because Arabic characters were getting counted as bytes, which quickly exceeded the former limit of 256.
=> Bump location redshift field to 1024 chars

script/heroku_deploy
This is something I picked up from @ashkan18 on Impulse. When you pass the `exit-code` flag and there are errors in migrations then the build will fail rather than silently failing. Seems like a best practice for any of our apps that use Heroku and Postgres.
=> Fail CI builds when migration errors

app/jobs/start_sync_job.rb, app/models/import.rb, app/models/organization_type.rb, lib/tasks/report_duplicate_organizations.rake, spec/jobs/start_sync_job_spec.rb, spec/models/organization_builder_spec.rb
Several small changes to address issues that arose during the last import, namely:
- Don't trigger a sync if all of the imported CSVs contain 100% errors
- Allow mixed-case strings in CSV tag names
- Add a failing (but skipped test) for a known bug which is creating duplicates (see #258)
- Add a new rake task `rake report:duplicate_organizations` to print out a count and a list of duplicate organizations
=> Misc maintainance

.circleci/config.yml, .circleci/heroku_deploy, .circleci/heroku_setup
This was done following this walkthrough:
https://circleci.com/docs/2.0/project-walkthrough/#deploying-to-heroku
I ended up generating a new SSH keypair and storing those creds in 1Password for posterity.
=> Fix deployment config for Circle 2.0

lib/tasks/temporary/factual_migration.rake
The cities didn't get migrated with factual, because that field is called `locality` (versus `city`) in the CSV. This migration sorts through those raw input records and adds city fields that are blank to existing locations.
Closes https://github.com/artsy/collector-experience/issues/353
Closes https://github.com/artsy/bearden/issues/263
=> Migrate cities for Factual imports

app/jobs/geocode_location_job.rb, app/models/location.rb, db/migrate/20170630163954_add_geocode_response_to_location.rb, spec/jobs/geocode_location_job_spec.rb
This PR follows up on https://github.com/artsy/bearden/pull/274, because, as @madeleineb pointed out, around ~38k records on Redshift still seem to be not geocoded. 
Looking deeper into the data, there are a lot of records that are marked as geocoded (they have non-nil latitudes and longitudes), but do not have meaningful data (nil city and country fields).
Unfortunately, checking for non-nil latitudes and longitudes does not return an accurate picture of whether or not a location has been geocoded. This is because, for imports, we allow users to include `latitude` and `longitude` fields. That means locations can have blank city or country fields and never be found by the geocoder. 
Other things might also be at play here. More below on that.
My solution is to add more visibility into …
=> Add field for Locations.geocode_response

Gemfile.lock, bin/setup
The gem `charlock_holmes` depends on ICU, and [it recommends](https://github.com/brianmario/charlock_holmes#homebrew) installing that via homebrew. You then have to point bundler to the correct directory as its a keg-only install. Lastly, the old release (0.7.3) doesn't seem to compile with the latest ICU, so I updated it and now `bundle install` works fine.
=> @jonallured: fix charlock_holmes gem setup

app/jobs/search_delete_job.rb, app/jobs/search_index_job.rb, app/models/concerns/searchable.rb, lib/tasks/elasticsearch.rake, spec/spec_helper.rb
Thanks for looking into the migration issues with the `elasticsearch:reindex` task. I made the two fixes you suggested and switched the workers away from `ActiveJob` to just use the `Sidekiq::Worker` module as we do in our other projects. The migration was working locally with this new setup.
ActiveJob doesn't support bulk pushing, as confirmed by Mike Perham [here](https://codexample.org/questions/721381/bulk-insert-using-activejob-and-sidekiq.c). We do want that ability in this context as it's more efficient when iterating over all the Organizations - it reduces Redis round-trip latency. 
Fixes https://github.com/artsy/bearden/issues/296.
=> @jonallured: fix elasticsearch reindex task

app/models/concerns/searchable.rb, config/secrets.yml
As discussed in https://github.com/artsy/bearden/issues/300, I use a new ENV var called `ELASTICSEARCH_ENV` to deduce the index name for Organizations.
Thanks for catching that issue - it recently caught me out in Diffusion too, so I really should have foreseen it.
I've updated the config vars in Heroku staging/production.
**Migration**
We need to re-migrate now I guess, since all our staging data incorrectly went into a production index. So on staging first, and then production, we should do this:
```ruby
Organization.reload_index! 
bundle exec rake elasticsearch:reindex
```
I'm happy to do that myself once this is merged, but let me know if you'd rather do it. 
Fixes https://github.com/artsy/bearden/issues/300
=> @jonallured: fix elasticsearch environments

app/graphql/types/organization_type.rb, app/models/organization.rb, app/models/organizations_query.rb, spec/graphql/search_spec.rb, spec/graphql/types/organization_type_spec.rb, spec/models/organization_spec.rb
Our representation of Organization objects via the Search API currently returns an unsorted array of names - API clients should only really see the top ranked name as this is the display name they should use when referring to the organization. The clients currently have no need for the alternate names, though we can add them to the schema if need be in future.
Here I index a `name` field in Elasticsearch as the authoritative (top ranked) name for an Organization, and additionally index other names in an `alternate_names` array as is our convention in other search indices. I've adjusted the search query to search on _all_ the names, but now the API only returns the `name` attribute. 
**Migration**
We need to recreate the index as we are scrapping the `names` field and adding the `name` and …
=> @jonallured: fix graphql organization schema to use top ranked name #migration

.circleci/config.yml
There's currently no guarantee the Elasticsearch process is running when we start the test suite, leading to occasional build failures. It can take a while to initialize the ES container fully. This command will block till ES is available on localhost at the default port, which I believe is our test setup.
=> @jonallured: ensure elasticsearch is up before running tests

app/controllers/api_controller.rb, spec/graphql/search_spec.rb
It turns out gravity has an [Auth API endpoint](https://github.com/artsy/gravity/blob/master/app/api/v1/me_auth_endpoint.rb#L20) that deals out JWT tokens to untrusted apps (like force) with a short expiry. This can theoretically be used to produce valid JWT tokens for Bearden knowing only the Bearden application ID, which is a security problem. 
While the Gravity API endpoint looks like a security hole, it can be useful for some apps who wish to allow access to a set of users from an untrusted app (like Impulse, which wants to allow some Force users access to their conversations inbox data, as Force is an untrusted app in this scheme). 
We've decided it's up to the destination app to validate app roles in its auth if it wishes to restrict access to trusted apps. This is the case with …
=> @jonallured: only allow jwt tokens from trusted apps

app/jobs/search_index_job.rb, app/models/concerns/searchable.rb
The return here only works if we use the `find_by` form, otherwise, `find` will just raise if it can't find the record and you'll never even hit the early return on the next line.
I know this because I was having issues with these jobs while testing #324 locally here on my laptop. This change fixed those jobs from failing, but might expose a different problem. I have a theory that these search indexing jobs are enqueued and then worked too quickly for Postgres. I think I was getting that exception about the record not being found because it was a race condition with the database insert!
If that's true, then this "fix" would actually break our search indexing and what we really need to do is find a way to introduce some delay between insertion and indexing.
Or maybe I'm missing something, …
=> Don't raise when the record can't be found

docs/API.md
I had some trouble today working with the Bearden API while smoke testing #329, so I spent some time improving the API docs. I was never actually able to get GraphQL IDE to work, but [graphlient](https://github.com/ashkan18/graphlient) worked like a charm!
=> Improve API docs

.circleci/config.yml
I think it's time - version 10 has been out for a while and is now GA on Heroku since mid-December. I started with my laptop:
```
$ brew upgrade postgres
```
In the post-upgrade message, there's a command to run that will upgrade your data, I ran that without error. I expected to have to reinstall the pg gem, but rake was green without it.
Next step is upgrading at Heroku, which I'll document next but let's see what happens at Circle.
=> Upgrade to latest Postgres

.circleci/heroku_deploy, Procfile
I hadn't heard of this, but I like this approach much better for ensuring database migrations happen before the dynos are in production.
https://devcenter.heroku.com/articles/release-phase
=> Use Heroku release phase for database migrations

.circleci/heroku_setup
With the switch to Arty's Ruby image, we can no longer rely on Heroku's CLI being installed for us.
=> Fix deployment

.circleci/config.yml
Oops! Forgot to ignore the build-and-test job when deploying to production, which was the whole point of removing the requirement from that job. 😝 
/cc @starsirius
=> Ignore the build and test job on release branch

.circleci/config.yml
It appears that CircleCI no longer maintains ES images, so this PR switches to another source.
=> Use better ES image
