artsy/bearden

README.md
=> Add Bearden to README.md

Procfile.dev, README.md
I love foreman, but when I run locally I want more feedback, so I've added a dev version of the Procfile.
=> Minor stuff

app/views/imports/index.html.haml, app/views/imports/new.html.haml, config/routes.rb
Would love feedback on that simple validation - cool or lame?
=> UI improvements

app/jobs/geocode_location_job.rb, db/migrate/20170403174222_add_country_city_to_location.rb, spec/jobs/geocode_location_job_spec.rb
Closes https://github.com/artsy/bearden/issues/146
=> Add country and city fields to db and populate with Geocoder

app/models/organization_resolver.rb, spec/models/organization_resolver_spec.rb
This is something that we've talked about before and just never got around to doing.
=> Break rankable ties with created_at timestamp

app/views/layouts/application.html.haml
=> Add nav for Syncs 

app/assets/stylesheets/application.scss, app/assets/stylesheets/spinner.sass, app/views/imports/new.html.haml, app/views/layouts/application.html.haml
=> Add spinner to imports page

app/models/csv_converter.rb, app/models/csv_transformer.rb, app/models/organization_resolver.rb, app/views/imports/new.html.haml, app/views/layouts/application.html.haml, lib/tasks/redshift.rake, spec/fixtures/one_complete_gallery.csv, spec/fixtures/one_partial_gallery.csv, spec/models/csv_converter_spec.rb, spec/models/csv_transformer_spec.rb, spec/models/organization_resolver_spec.rb, spec/models/raw_input_changes_spec.rb
- Fixes formatting in top nav
- Adds help section for Formatting CSVs
- Adds city and country to converter, transformer, and resolver. 
**NOTE: This PR requires Redshift tables to be updated!**
Closes #155
Fixes #173
=> Misc Fixes and Improvements

app/jobs/parse_csv_import_job.rb, spec/features/csv_import_spec.rb, spec/jobs/parse_csv_import_job_spec.rb
Pretty cool that this was caught because of Sentry and then fixed easily. Pretty not cool that I didn't smoke test this locally before doing my PR. Oh well, mistakes happen! 🤖
=> Fix: Faraday returns a response, not the body

Aptfile, app/jobs/parse_csv_import_job.rb, spec/features/csv_import_spec.rb, spec/jobs/parse_csv_import_job_spec.rb
=> Deploy: fix - Faraday returns a response, not the body

app/jobs/finish_sync_job.rb, app/jobs/start_sync_job.rb, spec/jobs/finish_sync_job_spec.rb
=> Super important changes to make things consistent

lib/tasks/redshift.rake
Took this directly from #194, so hopefully I got the syntax right! ❤️
=> Fix: grant permissions when creating Redshift db

app/models/csv_converter.rb, app/models/csv_transformer.rb, app/models/organization_resolver.rb, app/models/raw_input_changes.rb, app/views/imports/new.html.haml, db/migrate/20170418194850_add_in_business_to_organizations.rb, lib/tasks/redshift.rake, spec/models/csv_converter_spec.rb, spec/models/csv_transformer_spec.rb, spec/models/organization_resolver_spec.rb, spec/models/raw_input_changes_spec.rb
Well, after complaining about the state of `RawInputChanges` in #184, it was actually pretty easy to add this functionality, so maybe things aren't as bad as I feared?
=> Add in business column

.rubocop, .rubocop.yml, app/jobs/geocode_location_job.rb, app/models/email.rb, app/models/organization_tag.rb, app/models/source_resolver.rb, app/models/sync.rb, app/models/website.rb, config/environments/development.rb, lib/tasks/rubocop_pre_commit.rb
I wasn't aware this was a thing! Found it when looking through rosalind
and decided to activate it over here.
=> Use RuboCop's Rails mode

app/models/import.rb, app/models/import_micro_machine.rb, app/models/import_result.rb, app/views/imports/show.html.haml, spec/models/import_spec.rb
@madeleineb ran into this on production, so this is just a fix.
=> Fix import error link

app/models/email.rb, app/models/location.rb, app/models/organization_name.rb, app/models/organization_resolver.rb, app/models/phone_number.rb, app/models/website.rb
Addressing this from two angles:
* ensure that varchar-type fields have sensible limits on their length
* ensure that lists of things (tag and source names) don't exceed limits at export time
closes #215
=> Length validations

app/jobs/parse_csv_import_job.rb
After much trial and error, we discovered that we were not caching the data we were downloading and encoding, which caused this job to use a bananas amount of memory. This commit ensures that we only download and encoding the data once.
=> Cache csv data

Procfile, app/jobs/finalize_import_job.rb, app/jobs/finish_sync_job.rb, app/jobs/geocode_location_job.rb, app/jobs/organization_export_job.rb, app/jobs/parse_csv_import_job.rb, app/jobs/raw_input_transform_job.rb, app/jobs/start_sync_job.rb, app/jobs/sync_management_job.rb
=> Go back to using one worker

app/models/organization.rb, db/migrate/20170508211553_switch_to_string_for_in_business.rb, lib/tasks/redshift.rake, lib/tasks/temporary/in_business_data_migration.rake, spec/models/organization_spec.rb, spec/models/raw_input_changes_spec.rb
This commit also includes a temporary rake task to migrate existing data on production.
=> Use string column for in_business

lib/tasks/clear_sidekiq.rake, lib/tasks/temporary/in_business_data_migration.rake, lib/tasks/temporary/tag_type_data_migration.rake
After some conversations with @gnilekaw, I realized the `in_business` task was just plain wrong. It was also slow, so I improved that as well. While working on this, I realized that our task to clear Sidekiq was inadequate, so I improved that too.
=> Migration tweaks

lib/tasks/clear_sidekiq.rake
=> Actually clear Sidekiq queues

Gemfile.lock
Patch update to Rails and a routine bundle update for everything else.
=> Upgrade to Rails 5.1.3

.circleci/heroku_deploy, .circleci/heroku_setup
While working on a Rosalind deploy, I realized that I goofed this config for production so I'm just fixing that mistake.
=> Fix production deploy

app/helpers/application_helper.rb, app/views/layouts/application.html.haml
When I upgraded Bootstrap all the tests passed, but the navigation was broken and I didn't ever actually spin up a server and check. :cry:
This commit fixes that by adjusting a couple classes. I also fixed a mistake where we weren't highlighting syncs when that was the page you were on.
=> Fix broken nav

README.md, spellcheck.json
I'm trying to get good Peril feedback on spelling mistakes, so I'm tweaking the spelling list here and on artsy/artsy-danger.
=> Improve ignored words

.rubocop.yml, app/models/organization.rb, app/models/organization_resolver.rb, spec/graphql/search_spec.rb, spec/models/organization_resolver_spec.rb
See https://github.com/artsy/bearden/pull/317#discussion_r144834710, just like @yuki24 said, sorting in the database, then outside is ignoring sorting in the database.
Consolidating ranking into `OrganizationResolver`.
What we want is to sort by rank (lowest rank first), then by time (newest first).
=> Sort rankables by lowest rank first, then newest first, more explicitly.

.env.test, .rubocop.yml, Gemfile, Gemfile.lock, Rakefile, app/controllers/api_controller.rb, app/controllers/graphql_controller.rb, app/jobs/geocode_location_job.rb, app/jobs/start_sync_job.rb, app/models/import.rb, app/models/raw_input.rb, app/models/raw_input_changes.rb, app/models/sync.rb, bin/bundle, bin/rails, bin/rake, config/secrets.yml, spec/models/organization_builder_spec.rb, spec/rails_helper.rb
This started as a simple bundle update, but then I also fixed a couple things that had been bothering me. For one, I've had @joeyAghion's dotenv experience in the back of my mind and wanted to see what it would take to move this out of the test group on Bearden - turns out it's easy and I like it much better actually!!
I also finally removed a pending spec that I was keeping around for sentimental reasons and upgraded RuboCop, complying with a couple new cops.
=> Bundle update

Gemfile, Gemfile.lock
Addresses CVEs, see individual commits.
=> Update loofah and boostrap
